# Generated by Django 3.2.7 on 2021-10-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scope',
            new_name='Tag',
        ),
    ]
